{% set name = "diff-cover" %}
{% set version = "9.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diff_cover-{{ version }}.tar.gz
  sha256: c6c9f7f1eacd9019d118cafb75908445caa41a79f65f36f9f506c9626dbcbc70

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - diff-cover = diff_cover.diff_cover_tool:main
    - diff-quality = diff_cover.diff_quality_tool:main
  script: '{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv '

requirements:
  host:
    - pip
    - poetry-core >=1.0.7
    - python
  run:
    - jinja2 >=2.7.1
    - pluggy >=0.13.1,<2
    - pygments >=2.9.0,<3.0.0
    - python
    - chardet >=3.0.0
  run_constrained:
    - tomli >=1.2.1

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - flake8
    - pylint
    - pytest-cov
    - pycodestyle
    - pyflakes
    - pydocstyle
    - black
  imports:
    - diff_cover
    - diff_cover.violationsreporters
  commands:
    - pip check
    - diff-cover --help
    - diff-quality --help
    # Skipping test_get_src_path_clover cause it's using `datadir` package we don't supply
    - pytest -v -k "not test_get_src_path_clover" tests  # [not win]
    # Upstream is not testing windows, skipping all failing tests
    - pytest -v -k "not (
      test_git_path_selection or
      test_absolute_path or
      test_set_cwd_unicode or
      test_set_cwd_unicode_byte_passed_in_for_cwd or
      test_html_with_external_css or
      test_added_file_pycodestyle_consol or
      test_fail_under_console or
      test_fail_under_pass_console or
      test_added_file_pyflakes_console or
      test_added_file_pyflakes_console_two_files or
      test_added_file_pylint_console or
      test_quality or
      test_quality_pregenerated_report or
      test_report_root_path or
      test_violation_lines or
      test_get_src_path_clover
      )" tests  # [win]

about:
  home: https://github.com/Bachmann1234/diff-cover
  dev_url: https://github.com/Bachmann1234/diff-cover
  doc_url: https://github.com/Bachmann1234/diff-cover
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Automatically find diff lines that need test coverage.
  description: Automatically find diff lines that need test coverage.

extra:
  recipe-maintainers:
    - nicoddemus
