{% set name = "diff-cover" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diff_cover-{{ version }}.tar.gz
  sha256: 71a110ddd6ad1bb8e326699874ef2e9eb29e261a5978f963cf3e5776a58d531a

build:
  noarch: python
  number: 0
  entry_points:
    - diff-cover = diff_cover.diff_cover_tool:main
    - diff-quality = diff_cover.diff_quality_tool:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - jinja2 >=2.7.1
    - jinja2_pluralize
    - pygments
    - python
    - six >=1.6.1

test:
  imports:
    - diff_cover
    - diff_cover.violationsreporters
  commands:
    - diff-cover --help
    - diff-quality --help

about:
  home: https://github.com/Bachmann1234/diff-cover
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Automatically find diff lines that need test coverage.

extra:
  recipe-maintainers:
    - nicoddemus
