{% set name = "diff-cover" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diff_cover-{{ version }}.tar.gz
  sha256: 080dff104035e8a4844133ac1fb1055c80763699df207be817f3fe4211e4f5aa

build:
  noarch: python
  number: 0
  entry_points:
    - diff-cover = diff_cover.diff_cover_tool:main
    - diff-quality = diff_cover.diff_quality_tool:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - jinja2 >=2.7.1
    - jinja2_pluralize
    - pluggy
    - pygments
    - python >=3.5
    - chardet ==4.0.0

test:
  imports:
    - diff_cover
    - diff_cover.violationsreporters
  commands:
    - diff-cover --help
    - diff-quality --help

about:
  home: https://github.com/Bachmann1234/diff-cover
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Automatically find diff lines that need test coverage.

extra:
  recipe-maintainers:
    - nicoddemus
