{% set name = "diff-cover" %}
{% set version = "6.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diff_cover-{{ version }}.tar.gz
  sha256: f439baa4e48f974ca1887f4560878f3f71ea53590cce1431fa95f31f99c55df0

build:
  noarch: python
  number: 0
  entry_points:
    - diff-cover = diff_cover.diff_cover_tool:main
    - diff-quality = diff_cover.diff_quality_tool:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - poetry
    - python >=3.6    
  run:
    - jinja2 >=2.7.1
    - jinja2_pluralize
    - pluggy
    - pygments
    - python >=3.6
    - chardet >=3.0.0

test:
  imports:
    - diff_cover
    - diff_cover.violationsreporters
  commands:
    - diff-cover --help
    - diff-quality --help

about:
  home: https://github.com/Bachmann1234/diff-cover
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Automatically find diff lines that need test coverage.

extra:
  recipe-maintainers:
    - nicoddemus
