travis:
  secure:
    BINSTAR_TOKEN: g4E0P3sj1SSUDeQo4iORv9H/76+HGMhLGwU3Icuw0yjr3fWjRnLWZ2fmPkUA0VvbuGGcrzSNHUAp4/Zlc+yhO+BDqJmxN97xkN1xXTLnmqFGWtSsKtaLdPSWqTdq+hKdv4sozU2MwcrKzIpE+bd1xSz9B0kvjaWFyJNNpDSWe3Gv4I9haRc/tUTeUBpcelYqXbwVRsjFAnrETYi1sdzVEGqwV7T7csFgKvslS7cX1cXNzVNzVwHofmDyTeeJvjoNMkInOstjJrrOknjIdOp6p2JILSWs0HmgkWD4SgELAwN5lqYuT1fKvha6NQw6b9ef+i+8TfdSe1ACDoBAKsjNX5rj/JVgB2aq8ZKilAWlxkqwc+0Yfi2i7DeqFo5nwf0ivQhsM7lgadk5YRfp5y021AVAYGknvGrfJyuxLwX05nx01KqF5Dt2g6ZqYXX2oPBqw659Qz6JMrxisKDEekima93bPNH+DFQIqzUEzGP7y+aGdl5ZkChFoL/THTfjuq7OHX46aJVKRXC81EaJDWjwjJSKjF4/q0a0j008O6tKL4pvYOV+v6WfUoXDNpMFuOroUjTrxq2jW7vWueCC4xXOTThs20k4gmCBHqqOPq1LGX14+ggXx/qFIt8uD9+zQXh2YBr+lGjbB2F9Y8RFb0EfHT9/qxPV4QJgAzuI5x86ZAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
