travis:
  secure:
    BINSTAR_TOKEN: czog5ZiCTUnLlDrLNuLVBjQ7UOvvngtEaDQEJByKtCfC8Y6Uw1HjAe7E24FvmwAvzOCRqlGlbfyeE+rMkG3Mt3VXJaA0VZP1rsFO0OieyCV3JbXtzuGl6fdU/fnvEs+3YVicW8U/Jrt8x9wWGGLMHyPGPWOMn1jCYETymSj0eq6rLX0IACMqqEEAWR2KIihp44w9IP8NQSywJ1WJCkeW4vb1UTBzAyOY9a75PzBowRDFNSLLhnE1aJUDXwdzAuCAjJCn/TIcA+0mOjOezavSWt8im7CGoJZj+R/eHYz72Gae9ZjJfqqBqQcDOs+VfzEVqItq+JHarRmz3vUsByWxF8XDM23yfDycVJeHDeqTBfzxlRQys7oXyo5ikTs5RQ+eK+px4cjsAuUkhN3utCVOub5WVaPVfY6+ufypUpIo7Oj7r88uQ3AggvvE2wKG75X1BpLI6z8hE3FLJqHjOXfafbuYw+JqI1FSbmUjiYp86I+rYip06nysj9YOgIcgfbtjN9Er78OlDkJsSWuGpWhuX4BPQ+CA9Ut3URI90D9PTvjoOem7pjPsLB6ImoRzm6eSDGIyVJ5xw4HMqR+KtB/yqX/Iu7YOzOYKb5y78baos8zVlvnoYFkpPBNxgz1W+NvANi/BxOL+qomgkVyU+wAFeFuwaVj7KeXG3c4eTAPsVFY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
